## Activity 01: Use NumPy to compute the Mean, Median, and Variance

In this activity, you will consolidate the skills you've acquired in the last exercise and use NumPy to do some very basic mathematical calculations on our `normal_distribution` dataset.   
NumPy has a consistent API, so it should be rather easy to transfer your knowledge of the mean method to median and variance. 

#### Loading the dataset

In [1]:
# importing the necessary dependencies
import numpy as np

In [2]:
# loading the Dataset
dataset = np.genfromtxt('./data/normal_distribution.csv', delimiter=',')

In [3]:
# looking at the first two rows of the dataset
dataset[0:2]

array([[85., 90., 65., 75., 59., 71., 72., 75.],
       [80., 82., 85., 90., 71., 75., 65., 71.]])

---

#### Mean

In [4]:
# calculate the mean of the third row
np.mean(dataset[2])

76.5

In [5]:
# calculate the mean of the last column
np.mean(dataset[:,-1])

71.5

In [6]:
# calculate the mean of the intersection of the first 3 rows and first 3 columns
np.mean(dataset[0:3, 0:3])

83.55555555555556

---

#### Median

In [7]:
# calculate the median of the last row
np.median(dataset[-1])

80.5

In [8]:
# calculate the median of the last 3 columns
np.median(dataset[:, -3:])

71.5

In [9]:
# calculate the median of each row
np.median(dataset, axis=1)

array([73.5, 77.5, 77.5, 79. , 73. , 80.5])

---

#### Variance

In [10]:
# calculate the variance of each column
np.var(dataset, axis=0)

array([ 10.91666667,  60.47222222, 196.22222222,  91.88888889,
       149.55555556,  37.47222222, 129.25      ,  56.91666667])

In [11]:
# calculate the variance of the intersection of the last 2 rows and first 2 columns
np.var(dataset[-2:, :2])

51.6875

The values of the variance might seem a little bit strange at first.   
You can always go back to the topic that gives you a quick statistical overview to recap what you've learned so far.   

> **Note:**   
Just remember, the variance is not the standard deviation.   

Try calculation the standard deviation with NumPy to get a more descriptive value when comparing it to our dataset

In [12]:
# calculate the standard deviation for the dataset
np.std(dataset)

10.76885861975271