## Activity 03: Filtering, Sorting, and Reshaping

Following up on the last activity, we are asked to deliver some more complex operations.   
We will, therefore, continue to work with the same dataset, our `normal_distribution.csv`.

#### Loading the dataset

In [1]:
# importing the necessary dependencies
import numpy as np

In [32]:
# loading the Dataset
dataset = np.genfromtxt('./data/normal_distribution.csv', delimiter=',')

---

#### Filtering

To get better insights into our dataset, we want to only look at the value that fulfills certain conditions.   
Our client reaches out to us and asks us to provide lists of values that fulfills these conditions:
- all values greater than 95 (>95)
- all values that are between 80 and 95 (>80 and <95)
- the indices of all values that have a delta of less than 1 to 100 (x-100 < 1)

In [35]:
# values that are greater than 105
dataset[dataset>95]


array([100.,  96., 100.,  97., 100., 100.])

In [36]:
# values that are between 80 and 95
dataset[(dataset>80) & (dataset<95)]

array([85., 90., 82., 85., 90., 90., 90., 81., 82., 82., 87., 87., 83.,
       82., 89.])

> **Note:**    
Conditional filtering can be done either using the brackets syntax or NumPys `extract` method

In [74]:
# indices of values that have a delta of less than 1 to 100

#Solution-1
print("Solution-1:")
rows, cols = np.where(dataset == 100)  
print('row is :',rows)
print('col is :',cols)

my_list = []


# for (index,data) in np.ndenumerate(rows):       # Since we have no business with data, we can use _ (throaway variable)
for (index,_) in np.ndenumerate(rows):
     my_list.append([rows[index],cols[index]])

        
print(my_list)
    
#Solution-2
print("Solution-2:")
one_away_indices = [[rows[index], cols[index]] for (index, _) in np.ndenumerate(rows)]
print(one_away_indices)


Solution-1:
row is : [2 3 4 5]
col is : [2 2 7 7]
[[2, 2], [3, 2], [4, 7], [5, 7]]
Solution-2:
[[2, 2], [3, 2], [4, 7], [5, 7]]


---

#### Sorting

They also want to experiment with some more plotting techniques so they ask you to also deliver these datasets:
- values sorted in ascending order for each row
- values sorted in ascending order for each column
- the matrix of indices indicating the position in a sorted list of each value   
```
[3, 1, 2, 5, 4]  =>  [1, 2, 0, 4, 3]
```

In [86]:
# values sorted for each row
rows_sorted = np.sort(dataset,axis=1)
print(rows_sorted)
 




[[ 59.  65.  71.  72.  75.  75.  85.  90.]
 [ 65.  71.  71.  75.  80.  82.  85.  90.]
 [ 59.  61.  75.  80.  90.  90.  96. 100.]
 [ 63.  64.  77.  81.  82.  95.  97. 100.]
 [ 65.  67.  69.  72.  82.  87.  87. 100.]
 [ 58.  75.  76.  79.  82.  83.  89. 100.]]
2


> **Note:**   
By default, sorting will always be done along the last axis. In our case this is 1, leading to each row being sorted.

In [7]:
# values sorted for each column


In [8]:
# indices of positions for each row


---

#### Combining

After finishing their visualization and doing ask you to deliver a way they can incrementally add the split parts of the dataset to make sure it works with every subset, too.   
They want you to send them examples for:
- adding the second half of the first column
- adding the second column
- adding the third and last separate column


In [9]:
# split up dataset from activity03
thirds = np.hsplit(dataset, (3))
halfed_first = np.vsplit(thirds[0], (2))

# this is the part we've sent the client in activity03
halfed_first[0]

ValueError: array split does not result in an equal division

In [ ]:
# adding the second half of the first column to the data


In [ ]:
# adding the second column to our combined dataset


In [ ]:
# adding the third column to our combined dataset


> **Note:**    
The same results can be achieved with `np.concatenate` and `np.stack`.    
For both methods, you need to provide the axis onto which it should be appended.   
Depending on your preferences you might want to use those.

---

#### Reshaping

For their internal AI algorithms, they need the dataset in a reshaped manner that reduces the number of columns.   
They asked us to deliver the whole dataset in the following shapes:
- reshaped in a one-dimensional list with all values
- reshaped in a matrix with only 2 columns

In [ ]:
# reshaping to a list of values


In [ ]:
# reshaping to a matrix with two columns


> **Note:**   
-1 in the dimension definition means that it figures out the other dimension on its own