## Exercise 01: Loading a sample dataset and calculating the mean.

In this exercise, we will be loading the normal_distribution.csv dataset and calculate the mean of each row and each column with it.   
Our dataset will have several rows each containing floating point numbers around 100 with a standard deviation of 5.

Just to refresh your knowledge, a Gaussian normal distribution resembles this plot:   

[Normal Distribution ](https://en.wikipedia.org/wiki/Normal_distribution)   
![](https://upload.wikimedia.org/wikipedia/commons/9/9e/Normal_Distribution_NIST.gif)   


In our case, the vertical bar in the middle is the number 100.

#### Loading our dataset

In [1]:
# importing the necessary dependencies
import numpy as np

In [2]:
# loading the Dataset
dataset = np.genfromtxt('./data/grades.csv', delimiter=',')

In [3]:
# looking at the dataset
dataset

array([[ 65.,  71.,  49.,  77.,  56.,  59.,  51., 100.],
       [ 66.,  79.,  87.,  80.,  41.,  70.,  72.,  81.],
       [ 89.,  84.,  73.,  66.,  59.,  57.,  63.,  71.],
       [ 96.,  95.,  56.,  59.,  75.,  91.,  96.,  95.],
       [ 64.,  77.,  88.,  88.,  53.,  64.,  98.,  94.],
       [ 72.,  78.,  93.,  57.,  89.,  59.,  53.,  57.]])

---

#### After loading our dataset

To get a quick overview on our dataset we want to print out the "shape" of it.   
This will give us an output of the form (rows, columns)

In [4]:
# printing the shape of our dataset
dataset.shape

(6, 8)

In [5]:
# calculating the mean for the first row
np.mean(dataset[0])

66.0

In [6]:
# calculating the mean for the first column
np.mean(dataset[:, 0])

75.33333333333333

In [7]:
# mean for each row
np.mean(dataset, axis=1)

array([66.   , 72.   , 70.25 , 82.875, 78.25 , 69.75 ])

In [8]:
# mean for each col
np.mean(dataset, axis=0)

array([75.33333333, 80.66666667, 74.33333333, 71.16666667, 62.16666667,
       66.66666667, 72.16666667, 83.        ])

In [9]:
# calculating the mean for the whole matrix
np.mean(dataset)

73.1875

When looking at the mean values we can really nicely see the effect of calculating the mean of several vaules taken from a normal distribution.   
If we had even more data we would get even close to 100.